### ISSUE TITLE
Inquiry about the Release Date for NVS-solver (DGS)

### ISSUE THREAD

**Issue by RuihanLu** [ZHU-Zhiyu/NVS_Solver#10]
Thanks for your fascinating and outstanding work on the NVS-solver!

Do you have a plan to release code and checkpoint for NVS-solver (DGS)?

**Comment by mengyou2** [comment]
Hi, thanks for your interest in our project. I just uploaded the DGS code. As for the checkpoint, our method only utilizes the SVD model that was pre-trained and the nvs-solver pipeline is training-free.

**Comment by RuihanLu** [comment]
> Hi, thanks for your interest in our project. I just uploaded the DGS code. As for the checkpoint, our method only utilizes the SVD model that was pre-trained and the nvs-solver pipeline is training-free.

Thanks for your helpful answer! All the Best!
