### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by Dumeowmeow** [ZHU-Zhiyu/NVS_Solver#14]
Thank you for your great work! Did you use the diffusers code in src in your inference process?or directly pip install diffusers?

**Comment by ZHU-Zhiyu** [comment]
Hi @Dumeowmeow , thanks for your attention on our work. Yes, we install diffusers by pip. Please refer to our installation pipeline.
![image](https://github.com/ZHU-Zhiyu/NVS_Solver/assets/31000629/7d3dbbff-e6e9-48c6-8e94-61853135ce4c)

**Comment by Dumeowmeow** [comment]
Thanks for your detailed explanation!

**Comment by Dumeowmeow** [comment]
Sorry, I have another question. Why step_single twice in svd_interpolate_single_img_traj?

**Comment by mengyou2** [comment]
The first one is to compute the backward gradient in eq.14 and the second
one is to compute the denoised result.

Dumeowmeow ***@***.***>于2024年7月2日 周二下午5:41写道：
