### ISSUE TITLE
More dynamic examples

### ISSUE THREAD

**Issue by xizaoqu** [ZHU-Zhiyu/NVS_Solver#16]
Hi, can you provide the origin video shown in the dynamic part? Thanks.

**Comment by mengyou2** [comment]
Hi, thanks for your interest in our project.

I've uploaded the videos to google drive: https://drive.google.com/drive/folders/1tsRCQZNT9SFypNTzFvb3X4QANHM6EuuV?usp=drive_link

**Comment by xizaoqu** [comment]
> I've uploaded the videos to google drive: https://drive.google.com/drive/folders/1tsRCQZNT9SFypNTzFvb3X4QANHM6EuuV?usp=drive_link

Thanks. I've applied for the permission.

**Comment by mengyou2** [comment]
Oh sorry, i forgot to change the permission.
You can download directly now.
