### ISSUE TITLE
How to determine the radius

### ISSUE THREAD

**Issue by xizaoqu** [ZHU-Zhiyu/NVS_Solver#19]
Hi, I'm not familiar with the 3D camera. Could you tell me how to determine the major radius and minor radius? Does it have something to do with the depth map?

**Comment by mengyou2** [comment]
Thank you for your interest in our project. If you wanna try the circular trajectory and make the center object, such as the sculpture in the example image, always in the center of the generated video, the minor radius should be the depth value of the center object. The major radius determines how far the trajectory goes to right/left and you can give any value you like.

**Comment by xizaoqu** [comment]
Thanks for your explanation.
