### ISSUE TITLE
论文中似乎有个等式有点问题

### ISSUE THREAD

**Issue by ealicesora** [ZHU-Zhiyu/NVS_Solver#22]
等式10 右边第三项是不是多余了（他应该是与前一项等价的，前一项是9带入他的结果）
还是我哪里理解错了。
我是刚刚入门diffusion的萌新，求大佬赐教。
（不好意思，本人英语有点烂，就直接用中文问了）

**Comment by ZHU-Zhiyu** [comment]
![image](https://github.com/user-attachments/assets/5457b2f4-922f-4c9c-8f20-361e8b326f0e)
@ealicesora  您好，是指的这里标的第三项吗？，这个第三项是intensity function 的Taylor 级数，第二项是warping function的Taylor级数。Eq。10是把Eq. 9带入到Eq. 8之后在对warping function做泰勒展开的，因为warping function里面的GT depth通常来说是不知道的，咱们代入depth 估计网络的depth肯定是不准的，所以会有一些高阶余项。

**Comment by ealicesora** [comment]
谢谢大佬的回复，我现在理解了。

**Comment by ealicesora** [comment]
最开始我误认2是等式8中右边第二项带入9的结果，但现在明白了这是8中右边第一项带入9时，由于用了网络估计的depth带来的误差项
