### ISSUE TITLE
More single image examples

### ISSUE THREAD

**Issue by xrenaa** [ZHU-Zhiyu/NVS_Solver#23]
Hi, thanks for your great work!
Could you provide more single image examples you are using, e.g., Family, Palace, Church, Barn? Do you use the same intrinsic setting for all these example?

**Comment by mengyou2** [comment]
@xrenaa Thanks for your interest in our work! 
We provide the prompt images utilized in our experiments at this [https://drive.google.com/drive/folders/1eEB4U65RlEbqo4s4vTQSBH16929sGvQO?usp=sharing](url) For the camera intrinsic matrix, we primarily set it as 260 for all examples. We also find that the performance would be further improved (although it already outperforms SOTA methods), if we manually adjusted intrinsic matrices.  If you have any questions, feel free to ask!

**Comment by xrenaa** [comment]
Great! Thanks for your sharing!
