### ISSUE TITLE
About evaluation metrics

### ISSUE THREAD

**Issue by xizaoqu** [ZHU-Zhiyu/NVS_Solver#24]
Hi,

In the camera control section of this paper, three metrics are employed: ATE, RPE-T, and RPE-R.

Could you provide more details on the method used to estimate the camera pose? Specifically, I am interested in understanding which method is capable of producing an absolute trajectory. Additionally, if possible, could you share the code used for the evaluation?

Thank you!

**Comment by mengyou2** [comment]
Thanks for your interest in our project. We use particle-sfm (https://github.com/bytedance/particle-sfm) to estimate camera trajectories. They also provide code for computing metrics in the evaluation part on their GitHub.

**Comment by xizaoqu** [comment]
Thanks for your quick reply~
