### ISSUE TITLE
About metric depth estimation

### ISSUE THREAD

**Issue by zhuhz22** [ZHU-Zhiyu/NVS_Solver#26]
Hi, a question about depth estimation here:
In ` svd_interpolate_single_img_traj.py` from line 1034 to line 1046, it seems that you transform the *relativate depth* to *metric depth (absolute depth)* with some hyperparameters (e.g., `near=0.0001, far=500.`; `depth = 10000./depth `). Just wondering how are these hyperparameters decided? And if NVS-Solver is applied to generate novel views with other resolutions, is there any need to modify them?

**Comment by mengyou2** [comment]
hi, thanks for your interest in our project. The DepthAnything outputs disparity, so we need first calculate the inverse value. The 10000 is picked depending on the range of the disparity to get the depth in a normal range like 1-500.

For other resolution, you need to modify the w,h value in the code, as we set 1024, 576 by default. You may refer to https://github.com/ZHU-Zhiyu/NVS_Solver/issues/6
