### ISSUE TITLE
About GPU usage

### ISSUE THREAD

**Issue by zhao-yiqun** [ZHU-Zhiyu/NVS_Solver#4]
Hi,

thanks for the amazing project! I wonder how much GPU memory are used? I wonder whether it is possible to utilize less gpu Memory such as RTX4090 24GB? How should I adjust the parameters?

Thanks in Advance

**Comment by ZHU-Zhiyu** [comment]
Hi @zhao-yiqun , the proposed method is training-free. We optimize the video latent during the inference time. To run with less memory, you may try to use NVS-Solver (DGS) or reduce the video size. We will release NVS-Solver (DGS) in the next few days. 
We appreciate your patience.

**Comment by zhao-yiqun** [comment]
Thanks for your reply!
