### ISSUE TITLE
Error in svd_interpolate_two_img.py

### ISSUE THREAD

**Issue by d-irie** [ZHU-Zhiyu/NVS_Solver#5]
I think it is a great job !!
I have a question about svd_interpolate_two_img.py.
The variables tau_ and tau_p do not seem to be defined and I cannot run the code.

**Comment by mengyou2** [comment]
Thanks for your interest in our project and sorry for my mistake. The variable should be dist_t. I've revised the following line:
https://github.com/ZHU-Zhiyu/NVS_Solver/blob/a85bec261a17674fa7fa2f90719511d350c0420d/svd_interpolate_two_img.py#L1169

Please try again.

**Comment by d-irie** [comment]
Thank you for correcting the code.
The errors in the code are gone and I got great results !!
