### ISSUE TITLE
Use image diffusion model for interpolation

### ISSUE THREAD

**Issue by aejion** [ZHU-Zhiyu/NVS_Solver#7]
Hi! Great work!

I would like to know if it is possible for NVS-Solver to use an image diffusion model for interpolation. Additionally, could you explain why you chose to use a video diffusion model for interpolation?

**Comment by mengyou2** [comment]
Hi, @aejion, thanks for your interest in our project. SVD can predict a continuous video from a given image, thus ensuring better consistency between different generated viewpoints. This is a capability that image diffusion models lack.

**Comment by aejion** [comment]
Thanks for your quick reply!
